---
# handlers file for ansible-geonode

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes

- name: restart uwsgi
  service: name=uwsgi state=restarted
  sudo: yes

- name: init elasticsearch
  command: update-rc.d elasticsearch defaults 95 10
  tags: [elasticsearch]
