###
# Install GeoServer from Custom GeoNode Build 
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: install Tomcat 
  apt: pkg={{ item }} state=present
  sudo: yes
  with_items:
   - tomcat7 

- name: Download Geoserver (remote)
  sudo: yes
  get_url:
    dest=/var/lib/tomcat7/webapps/geoserver.war
    url={{ geoserver_url }}
    owner=0
    group=0
    mode=0644
